import React from "react";

import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../../public/images/instagram/aliProfile.jpg";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/components/HireMe";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ali Colak - Dev</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full ">
        <Layout className="pt-0">
          <div className="flex items-center justify-between w-full ">
            <div className="w-1/2">
              <Image
                src={profilePic}
                alt="Ali Colak"
                className="w-full h-auto rounded-[1.75em] mt-12"
                draggable="false"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center pl-16">
              <AnimatedText
                text="Turning Vision Into Reality With Code And Design."
                className="!text-6xl !text-left"
              />
              <p className="my-4 text-base font-medium ">
                As a skilled full-stack developer, I am dedicated to turning
                ideas into innovative web applications.
              </p>
              <div className="flex items-center self-start mt-2">
                <Link
                  href="/resume-july23.pdf"
                  alt="Resume"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                  border-2 border-solid border-transparent hover:border-dark"
                  download={true}
                >
                  Resume
                  <LinkArrow className="w-6 ml-2" />
                </Link>
                <Link
                  href="mailto:19acolak99@gmail.com"
                  className="ml-4 text-lg font-medium capitalize text-dark hover:underline underline-offset-4"
                >
                  {" "}
                  Contact me
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className="absolute right-8 bottom-8 inline-block w-20">
          <Image src={lightBulb} alt="Ali Colak" className="w-full h-auto" />
        </div>
      </main>
    </>
  );
}
